/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as BlockerRouteImport } from './routes/blocker'
import { Route as IndexRouteImport } from './routes/index'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
})
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
})
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
})
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
})
const BlockerRoute = BlockerRouteImport.update({
  id: '/blocker',
  path: '/blocker',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockerRoute: BlockerRoute,
  ChallengesRoute: ChallengesRoute,
  RewardsRoute: RewardsRoute,
  StatsRoute: StatsRoute,
  TimerRoute: TimerRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
